### ISSUE TITLE
Max Survey Limit

### ISSUE THREAD

**Issue by JohnNKing** [Spaatz965/MyPoSH#2]
https://github.com/Spaatz965/MyPoSH/blob/c838ffc5db25bdeda7d380f5471d920ac7038612/scriptsRSS/get-RSSRaffleWinnerList.ps1#L22

Hey @Spaatz965! Thinking about this again, the max valid survey submission count may be 11 (3 keynotes plus 9 tracks minus 1 for the final track of the day. Also not including 1 for the overall summit survey as that may also should not really be submitted prior to the drawings.) Does that sound right to you?

**Comment by JohnNKing** [comment]
🤔 And I suppose that's only true for the survey drawings. For the passport game (sponsor QR codes), the max is 2.

(And for all paid attendees and opt-in drawings, we can trust that there's only one entry per person.)

**Comment by Spaatz965** [comment]
@JohnNKing that particular line is a parameter. 8 is the default value if the parameter is not specified when running the script. For each of the use cases mentioned, that's handled each time the script is run.
